preset: recommended

finder:
  name:
    - "*.php"
  exclude:
    - "tests"
    - "vendor"

enabled:
  - concat_with_spaces

disabled:
  - align_double_arrow
  - short_array_syntax
  - concat_without_spaces