preset: recommended

finder:
  name:
    - "*.php"
  exclude:
    - "tests"
    - "vendor"

disabled:
  - blank_line_before_return
  - align_double_arrow
  - blank_line_after_opening_tag
  - phpdoc_align
  - simplified_null_return
  - single_quote
  - phpdoc_annotation_without_dot
  - trailing_comma_in_multiline_array
  - phpdoc_separation
  - concat_without_spaces