language: php
sudo: required
php:
  - 8.0
  - 8.1

env:
  CODECLIMATE_REPO_TOKEN: 909885d13238ccab94f6492ea52185141ed0f478883b7a5db1070a5c9830f666

before_script:
  - sudo locale-gen --no-archive fr_CA.UTF-8
  - locale -a
  - echo '' | pecl install apcu
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --stderr --verbose

after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: 909885d13238ccab94f6492ea52185141ed0f478883b7a5db1070a5c9830f666