language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml

after_script:
  - vendor/bin/test-reporter --coverage-report coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  code_climate:
    repo_token: 909885d13238ccab94f6492ea52185141ed0f478883b7a5db1070a5c9830f666